# config/_default/menus.en.toml

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10


[[main]]
  name = "Calendar"
  pageRef = "calendar"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/iameskild/ea-la-website"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

